repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.1.1
    hooks:
      - id: trailing-whitespace
        args:
          - --no-markdown-linebreak-ext
      - id: end-of-file-fixer
        files: \.(cabal|config|hs|md|py|txt|yaml)$
