steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true
  - imports:
      align: none
      list_align: new_line
      pad_module_names: false
      long_list_align: multiline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: false
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
  - tabs:
      spaces: 8
  - trailing_whitespace: {}

columns: 120
newline: native
